[config]
aspect_ratio = 1.77  # 16.0 / 9.0
image_width = 1200
samples_per_pixel = 20
max_depth = 50
look_from = [13, 2, 3]
look_at = [0, 0, 0]
vup = [0, 1, 0]
dist_to_focus = 10.0
aperture = 0.1
