[tool.poetry]
name = "rayt-python"
version = "0.1.0"
description = ""
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
build = "build.py"

[tool.poetry.scripts]
rayt = "rayt_python.main:run"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ipdb = "0.13.3"
ipython = "7.16.1"
mypy = "0.782"
pytest = "5.4.3"
scalene = "0.9.13"

[tool.black]
target-version = ['py38']

[tool.coverage.run]
source = ["./rayt_python"]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
indent = "    "
multi_line_output = 3
sections = "FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER"
use_parentheses = true
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
