[tool.black]
target-version = ['py38']

[tool.coverage.run]
source = ["./rayt_python"]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
indent = "    "
multi_line_output = 3
sections = "FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER"
use_parentheses = true

[build-system]
requires = ["setuptools", "wheel", "Cython"]
