[tool.poetry]
name = "rayt-python"
version = "0.1.0"
description = ""
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]

[tool.poetry.scripts]
rayt = "rayt_python:main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "0.780"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
